meta_product_name: "Gare au Covid"
meta_title: "Gare au Covid - Un jeu à l'ambiance pandémique !"
meta_description: "Un jeu d'ambiance so 2020, basé sur la Covid, pour réviser les gestes barrières en s'amusant."
meta_image: "gare-au-covid.png" # should exist in `app/assets/images/`
